import { z } from "zod";

export const createUserFormSchema = z.object({
  tenantId: z.string().trim().min(1, "Tenant is required."),
  username: z.string().trim().min(1, "Username is required."),
  department: z.string().trim().min(1, "Department is required."),
  title: z.string().trim().min(1, "Title is required."),
  userType: z.string().trim().min(1, "User type is required."),
  lifecycleStatus: z.string().trim().min(1, "Lifecycle status is required."),
  empId: z.string().trim().min(1, "Employee ID is required."),
  reason: z.string().trim().min(1, "Onboarding reason is required."),
  firstName: z.string().trim().min(1, "First name is required."),
  lastName: z.string().trim().min(1, "Last name is required."),
  email: z.string().trim().email("Enter a valid email address."),
  phone: z.string(),
  password: z.string().min(8, "Password must be at least 8 characters."),
  confirmPassword: z.string().min(1, "Confirm password is required."),
}).refine((values) => values.password === values.confirmPassword, {
  message: "Passwords do not match.",
  path: ["confirmPassword"],
});

export const createUserRequestSchema = z.object({
  userId: z.string().trim().min(1).optional(),
  username: z.string().trim().min(1),
  email: z.string().trim().email(),
  firstName: z.string().trim().min(1),
  lastName: z.string().trim().min(1),
  departmentId: z.string().trim().min(1),
  designation: z.string().nullish().optional(),
  isExternal: z.boolean().optional(),
  isActive: z.boolean(),
  initialPassword: z.string().min(8),
  phoneNumber: z.string().nullish(),
  tenantId: z.string().trim().min(1),
  userTrackId: z.string().nullish(),
  title: z.string().trim().min(1),
  userType: z.string().trim().min(1),
  lifecycleStatus: z.string().trim().min(1),
  empId: z.string().trim().min(1),
  supportingDocumentIds: z.array(z.string()).optional(),
  supportingDocuments: z.array(z.record(z.string(), z.unknown())).optional(),
  supportingDocumentType: z.string().nullish(),
  reason: z.string().trim().min(1),
});
