export {
  createCriticalParameter,
  createCriticalParameterLimit,
  createProductMaster,
  createIiotAsset,
  getCriticalParameter,
  getCriticalParameterLimits,
  getCriticalParameters,
  getCriticalParameterLimit,
  getProductMaster,
  getProductMasters,
  getIiotAsset,
  getIiotAssets,
  isMutableIiotMasterSection,
  setIiotMasterRecordActive,
  updateCriticalParameter,
  updateCriticalParameterLimit,
  updateProductMaster,
  updateIiotAsset,
} from "./iiotMaster.api";
export type {
  CriticalParameter,
  CriticalParameterLimit,
  CreateCriticalParameterLimitValues,
  CreateCriticalParameterValues,
  CreateIiotAssetValues,
  CreateProductMasterValues,
  IiotAsset,
  IiotAssets,
  IiotMasterRecord,
  IiotMasterSection,
  ProductMaster,
  UpdateCriticalParameterLimitValues,
  UpdateCriticalParameterValues,
  UpdateIiotAssetValues,
  UpdateProductMasterValues,
} from "./types";
