export {
  criticalParameterLimitSchema,
  criticalParameterLimitsSchema,
  criticalParameterSchema,
  criticalParametersSchema,
  createCriticalParameterLimitSchema,
  createCriticalParameterSchema,
  createIiotAssetSchema,
  createProductMasterSchema,
  iiotAssetSchema,
  iiotAssetsSchema,
  productMasterSchema,
  productMastersSchema,
  updateCriticalParameterLimitSchema,
  updateCriticalParameterSchema,
  updateIiotAssetSchema,
  updateProductMasterSchema,
} from "./iiot-master.schema";
